### ISSUE TITLE
Unsupported feature set; code is too new - SourceMod 1.11.0.6775

### ISSUE THREAD

**Issue by Sidicer** [GAMMACASE/MomSurfFix#19]
I've tried installing `MomSurfFix` on my older server which has `SourceMod 1.11.0.6775`

As your Readme states `SourceMod 1.11.0.6711 or higher` is required - which I technically have, but once the plugin is tried to be loaded I get an error `Unsupported feature set; code is too new`

Which SourceMod version is actually required for `Momentum Surf Fix v2 [1.1.5]` ?

**Comment by Sidicer** [comment]
As there is no need to have an older SourceMod version running can confirm upgrading to `6934` version fixed my issue

**Comment by GAMMACASE** [comment]
This remark assumes that you'd compile with SourceMod 1.11.0.6711 (including its includes from this version) and it'll work, the error you got seems strange tho, the requirement is here due to new sm api introduced in this version, not cuz of new sp features, so I guess that's just an unfortunate side effect as in release I compiled the code with more recent 1.11 version of sm.
